[package]
name = "texttopdf"
version = "0.1.0"
authors = ["iwot <iwmt@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
encoding_rs = "0.8.20"
